ar_clinic-mysql:
  container_name: ar_clinic-mysql
  image: mysql:5.7.9
  # volumes:
  #   - ~/volumes/jhipster/AR_clinic/mysql/:/var/lib/mysql/
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=ar_clinic
  ports:
    - "3306:3306"
  command: mysqld --lower_case_table_names=1
